### ISSUE TITLE
How do I get coordinates of ellipsoids in a packing?

### ISSUE THREAD

**Issue by ovgeorge** [malawski/ellipsoids#1]
I'm trying to find dense packing of two spheres types of different radii: 1.0, 2.0
I'm using a following config file    
```
	1.1  BASIC CONTROL DATA
=true if coordinates are to be saved    (         Lreslt_x)            1
	2.1  PRINCIPAL SYSTEM PARAMETERS
Number of particles                     (         No_parts)         2000
Number of species                       (       No_species)            2
Force scaling factor                    (          Epsilon)          0.1
Rotation scaling factor                 (          Eps_rot)         3.00
Diameter increasing factor              (        Diam_incr)         0.01
Number of cells in x direction          (       No_cells_x)           20
Number of cells in y direction          (       No_cells_y)           20
Number of cells in z direction          (       No_cells_z)           20
Contraction rate of outer diameter      (             Ntau)       102400
Initial packing density                 (            Pnom0)          0.8
Maximal number of steps                 (        Max_steps)     10000000
 = true if constant volume run          (          Leq_vol)            1
Number of parts (species 0)             (           Number)         1000
Diameter of parts (species 0)           (         Diameter)          1.3
Diameter of parts (species 0)           (         Diameter)          1.0
Diameter of parts (species 0)           (         Diameter)          1.0
Number of parts (species 1)             (           Number)         1000
Diameter of parts (species 1)           (         Diameter)          2.0
Diameter of parts (species 1)           (         Diameter)          2.0
Diameter of parts (species 1)           (         Diameter)          2.0
	4.1  PRINTOUT CONTROL
Number of lines per page                (        Npage_len)           56
number of steps between printouts       (      Nprint_step)          100
number of steps between coord. storage  (       Nrslt_step)      1000000
number of steps between rotations       (        Nrot_step)            1
```

And running it as 
./ellipsoids-openmp ell.dat.2 el.log 2
I think the coordinates to be saved into file "2", but there is only some binary data into it. How do I extract the coordinates of ellipsoids? I need it for FEM modeling of the porous structure.

**Comment by mbargiel57** [comment]
Hello,
You are right, the coordinates of ellipsoids are saved in binary format. There are two places where the binary file is written: the end of auxiliary_val() function and the save_x() function. From that you can figure out the structure of the file. The next step is to write a small program that would read the file and print (or whatever) the coordinates. If that seems hard please give me a message (at mbargiel@agh.edu.pl) and I will send you a program doing just that.
Sincerely,
Monika

**Comment by ovgeorge** [comment]
btw, I found ellipsoids.pov file, what is in it? There are all ellipsoids and their coordinates, what is it?

**Comment by mbargiel57** [comment]
It is PovRay file. PovRay is a raytracing program that I use to draw the actual ellipsoids in 3D. If you wish you can download it and see the results on the screen.

**Comment by ovgeorge** [comment]
So, in this .pov file is actual result of the packing? 

Also, thank you for great work, I will definitely cite it in my papers, this is very helpful.

**Comment by mbargiel57** [comment]
Yes, these are the actual coordinates and radii (scaled for the plotting though).
